# Generated by Django 5.2.7 on 2025-10-30 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('grupo_muscular', models.CharField(blank=True, choices=[('PEITO', 'Peito'), ('COSTAS', 'Costas'), ('OMBROS', 'Ombros'), ('BICEPS', 'Bíceps'), ('TRICEPS', 'Tríceps'), ('QUADRICEPS', 'Quadriceps'), ('POSTERIOR', 'Posterior'), ('PANTURRILHAS', 'Panturrilhas'), ('ABD', 'Abdômen'), ('ANT. BRAÇOS', 'Ant Braços'), ('GLUTEOS', 'Gluetos')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField(default=3, help_text='Número da série (1,2,3...)')),
                ('tipo', models.CharField(blank=True, choices=[('WS', 'Working Set'), ('DESC', 'Série de Descanso'), ('FAIL', 'Série até a Falha'), ('BO', 'Backoff Set')], help_text='Tipo da série (opcional)', max_length=10, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso usado em kg', max_digits=6, null=True)),
                ('descanso', models.PositiveIntegerField(default=60, help_text='tempo de descanso entre a serie')),
                ('observacao', models.TextField(blank=True, help_text='Notas adicionais sobre a série', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='workout.exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercicio',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='workout.treino'),
        ),
    ]
