# Generated by Django 5.2.7 on 2025-10-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='repeticoes',
            field=models.PositiveIntegerField(default=8, help_text='Número de repetições planejadas'),
        ),
    ]
