# Generated by Django 5.2.7 on 2025-10-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_serie_repeticoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='name',
            new_name='nome',
        ),
    ]
